# Generated by Django 3.2.7 on 2021-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poverki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_title', models.CharField(max_length=1024)),
                ('mit_number', models.CharField(max_length=32)),
                ('mit_title', models.CharField(max_length=128)),
                ('mit_notation', models.CharField(max_length=512)),
                ('mi_modification', models.CharField(max_length=128)),
                ('mi_number', models.CharField(max_length=128)),
                ('verification_date', models.CharField(max_length=32)),
                ('valid_date', models.CharField(max_length=32)),
                ('result_docnum', models.CharField(max_length=128)),
                ('applicability', models.CharField(max_length=10)),
            ],
        ),
    ]
